data:
  train: '' # if using MNIST, can download directly from cloud with train: 'download', test: 'download'
  val: ''
  batch_size: 128 # for test, batch_size//8 will be used.
  num_workers: 16
  type: '' # MNIST, CIFAR10, ImageNet
---
train:
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.00005
  decay:
    step: 150000
    gamma: 0.1
  summary_interval: 1
  checkpoint_interval: 1000
  evaluation_interval: 1000
---
model:
  channel: 78 # 'small regime'
  classes: 1000 # use 10 for MNIST, CIFAR10
  input_maps: 3 # 3 for ImageNet/CIFAR10, 1 for MNIST
  graph0: '' # example: 'ws-4-075-3.txt'
  graph1: ''
  graph2: ''
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
